### ISSUE TITLE
your diagram is not visible

### ISSUE THREAD

**Issue by lsnovich** [eladmunitz/OBWFinalPOC#16]
the code should be
```
![APIworkFlowDiagram](FlowChart.PNG)
```

**Comment by lsnovich** [comment]
in your case

```![API Work flow Diagram](FlowChart.PNG)```
renders 

![API Work flow Diagram](https://github.com/eladmunitz/OBWFinalPOC/blob/main/FlowChart.PNG)

**Comment by lsnovich** [comment]
I noticed you uploaded your image
and it is named FlowChart.PNG
on your page is the code
```![APIworkFlowDiagram](FlowChart.png)```

it should be
```![APIworkFlowDiagram](FlowChart.PNG)``` the filename is case sensitive

**Comment by eladmunitz** [comment]
I would never have suspected that!
I fixed the issue.

Am I missing anything else from your point of view?

Elad

**Comment by lsnovich** [comment]
fixed thanks!

**Comment by eladmunitz** [comment]
Why can I see this #16 on my list?
