### ISSUE TITLE
when indicating null or no option

### ISSUE THREAD

**Issue by lsnovich** [eladmunitz/OBWFinalPOC#20]
an empty string can be used  -  ```""```
but you need to make sure it is very clear to the person who is reading the doc
to do this it is best to state it in words

In all cases where it is possible to have no choice, ``""`` (an empty string) will be used. (or similar)

**Comment by lsnovich** [comment]
if you open the comment you can copy the code

**Comment by eladmunitz** [comment]
I don't understand what you are saying, and where is this dialog box is
found

Elad

**Comment by lsnovich** [comment]
If you click the three dots on my first comment and click edit you can copy the straight quotes to use in your doc.

**Comment by lsnovich** [comment]
![Screenshot from 2021-02-01 19-19-46](https://user-images.githubusercontent.com/38726461/106493935-7851ec80-64c2-11eb-9db7-2ebd28a48a03.png)

**Comment by lsnovich** [comment]
the last option for each row has quotes - in other tables you use none, pick one convention

**Comment by eladmunitz** [comment]
There is a difference between "none" and "".
"none" is a choice  - you don't want a side dish so you* picked* "none".
Now that there is no side dish - the size of the dish does not exist -
hence "".  (empty)

I think my logic is clear and consistent.

Elad
