### ISSUE TITLE
Authentication Section has issues

### ISSUE THREAD

**Issue by lsnovich** [eladmunitz/OBWFinalPOC#3]
While this API is fake, the contents shouldn't be erroneous. 

There are many ways to authenticate a user 

https://blog.cloud-elements.com/5-keys-building-integrations-2 - choose a method from here which fits the API  You are documenting

**Comment by eladmunitz** [comment]
I chose JSON Web Token (JWT) for my API.
I am not clear as to WHY Authentication is needed for an API that orders a burger.
