### ISSUE TITLE
Error Codes - DO Not Make it up on "known" error codes

### ISSUE THREAD

**Issue by lsnovich** [eladmunitz/OBWFinalPOC#4]
Some HTTP request Codes
are  known and used world wide.
Do not change the meaning of these codes to something else.
If you want custom codes, create one within the same range, but a different number.

**Comment by eladmunitz** [comment]
I don't see what I did wrong. 
I only used existing error codes as they should apply to the diner's API

**Comment by lsnovich** [comment]
For example 

404 - Not Found | The meal modifications you requested were not found. Order cannot be completed as is

a 404 means the page you are looking for cannot be found (the link is broken), nothing more
It does not mean there is something missing from the kitchen or the meal is not available in the way you ordered it.
you can use another error code for this.
